algo: "ppo"
policy: "CnnPolicy"
levels:
  - "SuperMarioBros-1-1-v0"

resize: 84
num_stack: 4
num_skip: 4
render_mode: None
action_set: "SIMPLE_MOVEMENT"

learning_rate: 0.00025
total_timesteps: 1000000   
seed: 67
